name: 'Go test action by theritikchoure'
author: 'theritikchoure'
description: 'Check licenses in your go package'

inputs:
  runVendor:
    description: "If set false, action won't do `go mod vendor`"
    default: true

branding:
  icon: file-text
  color: green
runs:
  using: "composite"
  steps:
    - name: Set up Go 1.16
      uses: actions/setup-go@v2
      with:
        go-version: 1.16
      id: go

    - name: Run Check
      run: go run ${{ github.action_path }}/main.go
      shell: bash